// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/battle-scene/BattleScene.tsx": () => import("../components/mockups/battle-scene/BattleScene.tsx")
};
